name: Build image for v1

on:
  push:
    branches:
      - master

env:
  V1_IMAGE_NAME: jomon
  V1_IMAGE_TAG: latest

jobs:
  image-v1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/traptitech/${{ env.V1_IMAGE_NAME }}:${{ env.V1_IMAGE_TAG }}
